version: '3.8'

services:
  mysql:
    image: mysql/mysql-server
    container_name: my_sql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    restart: always